### ISSUE TITLE
The 'Result Location' does not always work

### ISSUE THREAD

**Issue by urvashisingh** [electric-cloud/EC-EC2#16]
This applies to all the procedures in EC-EC2 so its not specific to the new procedures added by Clogeny. The 'Result Location' only works if its value is specified relative to a known entity, for example, '/myJob/result' works but 'result' does not. Can we define a standard convention for the 'Result Location' parameter than a relative value such as 'result' will always be relative to 'myJob'.

**Comment by horodchukanton** [comment]
This will be tracked in corresponding JIRA
