### ISSUE TITLE
Fails to create credential when username has "@" symbol

### ISSUE THREAD

**Issue by dhubbell** [electric-cloud/EC-EC2#76]
When using the configure screen to create a configuration, the background job fails on the "CreateAndAttachCredential" step with an error like the following:

> Possible unintended interpolation of @somos in string at /tmp/ecmdrAgent/agent.8GJ54725Q38AHNEO.run-0e2bbbcf-056a-11e9-9ecc-0eed8868e72c-0e503389-056a-11e9-8849-0a6c81224ce8.cmd line 76.
> Global symbol "@somos" requires explicit package name at /tmp/ecmdrAgent/agent.8GJ54725Q38AHNEO.run-0e2bbbcf-056a-11e9-9ecc-0eed8868e72c-0e503389-056a-11e9-8849-0a6c81224ce8.cmd line 76.
> Execution of /tmp/ecmdrAgent/agent.8GJ54725Q38AHNEO.run-0e2bbbcf-056a-11e9-9ecc-0eed8868e72c-0e503389-056a-11e9-8849-0a6c81224ce8.cmd aborted due to compilation errors.

Editing that step in the CreateConfiguration procedure by enclosing the reference to $[/myJob/launchedByUser] in single quotes instead of the existing double quotes resolves this issue.

**Comment by horodchukanton** [comment]
Thanks for the issue. Changes are already addressed.
